module.exports={
    devServer:{
         open:true,
         port:8801,
         host:"127.0.0.1",
         proxy:{
             '/api':{
                 target:"http://localhost:8801",
                 changeOrigin:true,
                 pathRewrite:{
                     "^/api":''
                 }
             },

         }
    },
    productionSourceMap:false,
    lintOnSave:false
}